name: Java CI with Gradle & Deploy to EC2

# main 브런치에 push가 되면 아래의 flow가 실행됩니다.
on:
  push:
    branches: [ "develop-be-docker" ]

# flow에서 사용할 변수 같은 느낌입니다.
env:
  working-directory: ./be

permissions:
  contents: read


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    # 아래의 flow들이 차례대로 실행됩니다.
    steps:
      # 1) 기본 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # 2) JDK 11 셋팅
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # 3) gradlew 권한 설정
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ${{ env.working-directory }}

      - run: touch ./be/src/main/resources/application.properties
      - run: echo "${{ secrets.APPLICATION }}" > ./be/src/main/resources/application.properties
      - run: cat ./be/src/main/resources/application.properties

      # 4) gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build
        working-directory: ${{ env.working-directory }}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jmdb-be


      - name: Pull and restart Docker Container
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/jmdb-be
            sudo docker stop jmdb-be
            sudo docker run -d --rm --name jmdb-be -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/jmdb-be

            